title: AWS Cloud Security Portfolio
description: Architecture documentation for Consumer Wellness, Education, and Medicine Cloud Security projects.
theme: jekyll-theme-cayman
github:
  is_project_page: true
